import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Montserrat } from "next/font/google";
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const montser = Montserrat({
  subsets: ["latin"],
  variable: "--font - montser",
  weight: ["100", "200", "300", "400", "900"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${montser.variable} ${inter.variable}`}>
        {children}
      </body>
    </html>
  );
}
